version: '2'
############ 공통######################
volumes:
  data:

########################################
services:
  portainer:
    image: portainer/portainer-ce
    container_name: "DockerManager"
    restart : always
    ports:
      - "9999:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
